import network from "./network";

export const {
    baseURL,
    contentType,
    accept,
    xRequestedWith,
    errorNetworkCode,
    messageDuration,
    timeout,
    okCode,
    createdCode,
    notContentCode,
    movedPermanentlyCode,
    badRequestCode,
    unauthorizedCode,
    forbiddenCode,
    notFoundCode,
    methodNotAllowCode,
    requestTimeoutCode,
    payloadTooLargeCode,
    pageExpiredCode,
    unprocessableEntityCode,
    tooManyRequestsCode,
    internalServerCode,
    serviceUnavailableCode,
} = network;
